apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chromeNode.service.name }}
  labels:
    {{- include "insider-tests.chromeNodeLabels" . | nindent 4 }}
spec:
  type: {{ .Values.chromeNode.service.type }}
  selector:
    {{- include "insider-tests.chromeNodeSelectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.chromeNode.service.port }}
    targetPort: {{ .Values.chromeNode.service.targetPort }}
