apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "insider-tests.fullname" . }}-config
  labels:
    {{- include "insider-tests.labels" . | nindent 4 }}
data:
  CHROME_SERVICE_URL: "http://{{ .Values.chromeNode.service.name }}:{{ .Values.chromeNode.service.port }}/wd/hub"
  APP_BASE_URL: {{ .Values.testController.env.appBaseUrl | quote }}
  RUNNING_IN_CONTAINER: {{ .Values.testController.env.runningInContainer | quote }}
